ginger/projects/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import (BooleanField, DateTimeField, EmailField, FileField,
                     SelectField, StringField, SubmitField, TextAreaField)

from wtforms.validators import DataRequired


class IssueForm(FlaskForm):

    issue_type = SelectField('Issue Type', choices=[(
        'bug', 'Bug'), ('task', 'Task')], validators=[DataRequired()])

    summary = StringField('Summary', validators=[DataRequired()])
    description = TextAreaField('Description')

    assignee = StringField('Assignee')

    labels = StringField('Labels')

    attachment = FileField('Attachment', validators=[
        FileAllowed(['jpg', 'png', 'pdf', 'docx', 'doc', 'txt'])])

    flagged = BooleanField('Flagged')

    submit = SubmitField('Create Issue')


class ProjectForm(FlaskForm):

    name = StringField('Project Name', validators=[DataRequired()])
    submit = SubmitField('Create Project')

class MemberForm(FlaskForm):
    
    name = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Add Member')


class CommentForm(FlaskForm):

    content = StringField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class SprintForm(FlaskForm):

    name = StringField('Sprint Name', validators=[DataRequired()])

    duration = SelectField('Duration')
    start_date = DateTimeField(
        'Start Date', format="%d/%m/%y", validators=[DataRequired()])
    end_date = DateTimeField(
        'End Date', format="%d/%m/%y", validators=[DataRequired()])

    goal = TextAreaField('Goal')

    submit = SubmitField('Start Sprint')

ginger/projects/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, current_app
from ginger import db
from ginger.projects.forms import ProjectForm, IssueForm, CommentForm, MemberForm
from ginger.projects.utils import save_attachment
from ginger.models import Project, Issue, Comment, User
from flask_login import current_user
from datetime import datetime


projects = Blueprint('projects', __name__)


@projects.route('/project/new', methods=['GET', 'POST'])
def create_project():
    form = ProjectForm()

    if form.validate_on_submit():

        project = Project(name=form.name.data,
                          created_by=current_user.username)
        current_user.projects.append(project)

        db.session.add(project)
        db.session.commit()
        flash('Your project has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('new_project.html', form=form)


@projects.route('/project/<string:project_name>',methods=['GET','POST'])
def get_project(project_name):
    form = MemberForm()
    project = Project.query.filter_by(name=project_name).first_or_404()
    
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.name.data).first()
        if user:
            if project.is_member(user):
                flash('Already a member !', 'warning')
                return redirect(url_for('projects.get_project',project_name=project_name))
            
            project.add_member(user)
            db.session.commit()
        else:
            flash("User doesn't exist !", 'danger')
            form = MemberForm()
            return redirect(url_for('projects.get_project',project_name=project_name,form=form))

    return render_template('project.html', project=project,form=form)

@projects.route('/project/<string:project_name>/user/<string:username>', methods=['DELETE'])
def add_new_member(project_name,username):
    project = Project.query.filter_by(name=project_name).first_or_404()
    user = User.query.filter_by(username=username).first_or_404()
    if project.is_member(user):
        project.remove_member(user)
        db.session.commit()
        return '', 204

""" @projects.route('/project/<string:project_name>/members')
def get_members(project_name):
    
    project = Project.query.filter_by(name=project_name).first_or_404()
    
    members = projects.members.all()
    
    return  """
    
'''
project/<string:project_name>/user/<string:username> POST
project/<string:project_name>/user/<string:username> DELETE
project/member/remove
'''

@projects.route('/project/<int:id>/update')
def update_project():
    pass


@projects.route('/project/<int:id>/delete')
def delete_project():
    pass


@projects.route('/issue/new', methods=['POST', 'GET'])
def create_issue():
    form = IssueForm()

    if form.validate_on_submit():

        project_name = request.args.get('project')

        if project_name:

            parent_project = Project.query.filter_by(
                name=project_name).first_or_404()

            if form.attachment.data:
                attachment_name = save_attachment(form.attachment.data)
            else:
                attachment_name = ''

            issue = Issue(created_by=current_user.username, issue_type=form.issue_type.data,
                          summary=form.summary.data, description=form.description.data, assignee=form.assignee.data, labels=form.labels.data, attachment=attachment_name, flagged=form.flagged.data, parent_project=parent_project, issue_author=current_user)

            db.session.add(issue)
            db.session.commit()

            flash('Your issue has been created!', 'success')
            return redirect(url_for('projects.get_project', project_name=project_name))

    return render_template('new_issue.html', form=form)


@projects.route('/issue/<int:id>', methods=['GET', 'POST'])
def get_issue(id):

    comment_form = CommentForm()
    issue = Issue.query.filter_by(id=id).first_or_404()

    comments = Comment.query.order_by(Comment.date_created.desc()).filter_by(
        comment_parent=issue).all()
    comment_list = []
    for comment in comments:
        user_id = comment.user_id
        user = User.query.get(user_id)
        comment_list.append({
            'user': user,
            'comment': comment
        })

    # print(comment_list)

    if comment_form.validate_on_submit():

        comment = Comment(content=comment_form.content.data, date_created=datetime.utcnow(),
                          comment_author=current_user, comment_parent=issue)

        db.session.add(comment)

        db.session.commit()

        return redirect(url_for('projects.get_issue', id=id))

    return render_template('issue.html', issue=issue, comments=comment_list, form=comment_form)


@projects.route('/issue/<int:id>/update')
def update_issue():
    pass


@projects.route('/issue/<int:id>/delete')
def delete_issue():
    pass

ginger/users/routes.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required, login_user, logout_user
from ginger import bcrypt, db
from ginger.models import User

from ginger.users.forms import (LoginForm, RegistrationForm,
                                UpdateAccountForm, ResetPasswordRequestForm, ResetPasswordForm)
from ginger.users.utils import save_picture
from ginger.users.email import send_password_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    if form.validate_on_submit():

        user = User(username=form.username.data,
                    email=form.email.data)
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()

        flash(
            f"Account successfuly created for {form.username.data}", "success")

        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)

            # this route when user was redirected from a page to login
            # we are sending the user back to that page
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateAccountForm()

    if form.validate_on_submit():

        if form.picture.data:
            picture_file = save_picture(form.picture.data)  # return file name
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()

        flash('Your account has been updated!', 'success')

        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    #image_file = current_user.get_avatar()
    # print(image_file)

    return render_template('account.html', title=current_user.username, nonav=True, form=form)


@users.route('/reset-password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            print('User Requesting password rest exists .')
            send_password_reset_email(user)
            print('Email Sent to user .')

        flash('Check your email for the instructions to reset your password')
        return redirect(url_for('users.login'))

    return render_template('reset_password_request.html',
                           title='Reset Password', form=form)


@users.route('/reset-password/<token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('main.index'))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.new_password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    
    return render_template('reset_password.html', form=form)

""" 
@users.route('/user/<string:username>')
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)

    user = User.query.filter_by(username=username).first_or_404()

    posts = Post.query.filter_by(author=user).order_by(
        Post.date_created.desc()).paginate(per_page=5, page=page)

    return render_template('user_posts.html', user=user, posts=posts) """

ginger/templates/account.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card profile-card">
                <div class="card-header">
                    <h5 class="card-title">@{{ current_user.username }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{current_user.email}}</h6>
                    <div class="container">
                        <div class="row">
                            <div class="col"><img class="profile-img" src="{{current_user.get_avatar()}}" alt=""></div>
                        </div>

                    </div>
                    <p class="my-2 text-muted">Joined : {{moment(current_user.account_created).format('LLL')}}</p>

                </div>
            </div>





            <div class="card form-card">
                <div class="card-body content-section">
                    <form method="POST" action="" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Update Account</legend>
                            <div class="form-group">
                                {{ form.username.label(class="form-control-label") }}

                                {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}

                                {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.picture.label() }}
                                {{ form.picture(class="form-control") }}
                                {% if form.picture.errors %}
                                {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="form-group my-2">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock content %}

ginger/templates/home.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            {% if projects %}
            <div class="container my-4">
                <ul class="list-group">
                    <li class="list-group-item">
                        <a class="btn btn-success" href="{{url_for('projects.create_project')}}">Create New Project</a>
                    </li>
                    {% for project in projects %}
                    <li class="list-group-item">
                        <div class="card">
                            <div class="card-body">
                                <a class="btn" href="{{url_for('projects.get_project',project_name=project.name)}}">
                                    <h5 class="card-title display-4">{{project.name}}</h5>
                                </a>
                                <p class="card-subtitle">{{ moment(project.date_created).format('LLL')}}</p>
                            </div>

                        </div>

                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% else %}
            <div class="container my-4">
                <ul class="list-group">
                    <li class="list-group-item">
                        <a class="btn btn-success" href="{{url_for('projects.create_project')}}">Create New Project</a>
                    </li>
                </ul>
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

ginger/templates/index.html
{% extends 'layout.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card form-card">
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a class="btn btn-block btn-success" href="{{url_for('users.login')}}">Log In</a>
                        </li>

                        <li class="list-group-item">
                            <a class="btn btn-block btn-outline-success" href="{{url_for('users.register')}}">Sign
                                Up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ginger/templates/issue.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card mx-auto my-4 sticky-top">
                <img src="{{url_for('static',filename='project-task-list.jpg')}}" alt="" class="card-img-top">
                <div class="card-header">
                    <h5 class="card-title">{{issue.summary}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{issue.id}}</h6>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Card link</a>
                </div>
                <div class="card-body">
                    <h6 class="text-muted">Description</h6>
                    <p>{{issue.description}}
                    </p>
                </div>

                {% if issue.flagged%}
                <div class="card-footer">
                    <span class="text-danger">Flagged</span>
                </div>
                {% endif %}


            </div>


        </div>
        <div class="col-md">

            <div class="container mx-auto my-4">
                <div class="container">
                    <h6 class="">Discussion</h6>
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">@{{current_user.username}}</span>
                            </div>




                            {% if form.content.errors %}

                            {{ form.content(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                            {% else %}

                            {{ form.content(class="form-control") }}

                            {% endif %}




                            <div class=" input-group-append">
                                {{ form.submit(class="btn btn-outline-info") }}
                            </div>
                        </div>


                    </form>


                    <ul class="list-group list-group-flush my-4">
                        {% for comment_item in comments %}
                        <li class="list-group-item">
                            <span class="text-muted">@{{comment_item['user'].username}} :</span>
                            {{comment_item['comment'].content}}
                        </li>
                        {% endfor %}

                    </ul>

                </div>
            </div>


        </div>
    </div>
</div>
{% endblock %}

ginger/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{url_for('static',filename='styles/main.css')}}">

    {% if title %}
    <title>{{title}} - Ginger</title>
    {% else %}
    <title>Ginger - Project Management</title>
    {% endif %}



</head>

<body>
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}}">
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% if nonav == NULL %}
    <div class="container-fluid mb-2">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{url_for('main.home')}}">Ginger</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">

                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.account')}}">@{{current_user.username}}</a>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                    </li>
                    {% endif %}


                </ul>
            </div>
        </nav>
    </div>
    {% endif %}


    {% block content %}

    {% endblock %}

    <!-- Scripts -->
    <!-- JavaScript Bundle with Popper -->
    <!--     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script> -->

    <!-- Jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Moment.js -->
    {{ moment.include_moment() }}

</body>

</html>

ginger/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card form-card">
                <div class="card-body content-section">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Log In</legend>
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.password.label(class="form-control-label") }}
                                {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-check">
                                {{ form.remember(class="form-check-input") }}
                                {{ form.remember.label(class="form-check-label") }}
                            </div>
                        </fieldset>
                        <div class="form-group my-2">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                        <small class="text-muted ml-2">
                            <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                        </small>
                    </form>
                </div>
                <div class=" card-footer border-top pt-3">
                    <small class="text-muted">
                        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ginger/templates/new_project.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card form-card">
                <div class="card-body content-section">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">New Project</legend>
                            <div class="form-group">
                                {{ form.name.label(class="form-control-label") }}
                                {% if form.name.errors %}
                                {{ form.name(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.name.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.name(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>


                        </fieldset>
                        <div class="form-group my-2">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

ginger/templates/project.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h5 class="display-4">
                            {{project.name}}
                        </h5>
                        <p class="card-subtitle text-muted">{{ moment(project.date_created).format('LLL') }}</p>
                        <a class="btn btn-success m-2"
                            href="{{url_for('projects.create_issue', project=project.name)}}">Start Chat</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row my-2">
        <div class="col-sm-4">

            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">

                    <div class="form-group">

                        {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid",placeholder="username", value="") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.name(class="form-control form-control-lg",placeholder="username") }}
                        {% endif %}
                    </div>


                </fieldset>
                <div class="form-group my-2">
                    {{ form.submit(class="btn btn-outline-success") }}
                </div>

            </form>
            <div class="ul list-group">
                <!--     <li class="list-group-item">
                    <a class="btn btn-success" href="{{url_for('projects.create_issue', project=project.name)}}">Add New
                        Member</a>
                </li> -->
                {% for m in project.members %}
                <li class="list-group-item">
                    {{m.username}}
                </li>
                {% endfor %}
            </div>

        </div>
        <div class="col-sm-8">
            <ul class="list-group">
                <li class="list-group-item">
                    <a class="btn btn-success" href="{{url_for('projects.create_issue', project=project.name)}}">Create
                        New
                        Issue</a>
                </li>
                {% for i in project.issues %}
                <li class="list-group-item">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{url_for('projects.get_issue',id=i.id)}}" class="btn">
                                <h5 class="card-title display-5">
                                    {{i.summary}}
                                </h5>
                            </a>

                            <p class="card-subtitle text-muted">
                                {{i.issue_type}}
                            </p>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>

        </div>
    </div>
</div>
{% endblock %}